config/routes.rb
Rails.application.routes.draw do
  # Resources
  resources :usertracks
  resources :contacts

  # Home
  get 'home/index'
  root :to =>"usertracks#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :email, uniqueness: true

end

app/models/usertrack.rb
class Usertrack < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :except => [:update]


  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@contacts = Contact.all
  	@title = "Contatos"
  end
end

app/controllers/usertracks_controller.rb
class UsertracksController < ApplicationController
  before_action :set_usertrack, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :except => [:update]

  # GET /usertracks
  # GET /usertracks.json
  def index
    @usertracks = Usertrack.all.limit(50).order('id desc')
    @title = "User Tracks"
  end

  # GET /usertracks/1
  # GET /usertracks/1.json
  def show
  end

  # GET /usertracks/new
  def new
    @usertrack = Usertrack.new
  end

  # GET /usertracks/1/edit
  def edit
  end

  # POST /usertracks
  # POST /usertracks.json
  def create
    @usertrack = Usertrack.new(usertrack_params)

    respond_to do |format|
      if @usertrack.save
        format.html { redirect_to @usertrack, notice: 'Usertrack was successfully created.' }
        format.json { render :show, status: :created, location: @usertrack }
      else
        format.html { render :new }
        format.json { render json: @usertrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usertracks/1
  # PATCH/PUT /usertracks/1.json
  def update
    respond_to do |format|
      if @usertrack.update(usertrack_params)
        format.html { redirect_to @usertrack, notice: 'Usertrack was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertrack }
      else
        format.html { render :edit }
        format.json { render json: @usertrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usertracks/1
  # DELETE /usertracks/1.json
  def destroy
    @usertrack.destroy
    respond_to do |format|
      format.html { redirect_to usertracks_url, notice: 'Usertrack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usertrack
      @usertrack = Usertrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usertrack_params
      params.require(:usertrack).permit(:guid, :url, :datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/usertracks_helper.rb
module UsertracksHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>#</th>
    <th>Nome</th>
    <th>Contato</th>
  </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.id %></td>
        <td><%= contact.name.capitalize %></td>
        <td><%= contact.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/favicon.ico">

  <title>Dashboard Template for Bootstrap</title>

  <!-- Bootstrap core CSS -->
  <link href="/bootstrap-dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="/bootstrap-dist/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/bootstrap-dist/css/dashboard.css" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="/bootstrap-dist/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="/bootstrap-dist/js/ie-emulation-modes-warning.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Dashboard - User Tracking</a>
    </div>
    <!--<div id="navbar" class="navbar-collapse collapse">-->
      <!--<ul class="nav navbar-nav navbar-right">-->
        <!--<li><a href="#">Dashboard</a></li>-->
        <!--<li><a href="#">Settings</a></li>-->
        <!--<li><a href="#">Profile</a></li>-->
        <!--<li><a href="#">Help</a></li>-->
      <!--</ul>-->
      <!--<form class="navbar-form navbar-right">-->
        <!--<input type="text" class="form-control" placeholder="Search...">-->
      <!--</form>-->
    <!--</div>-->
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li><a href="/home/index" class="mdl-layout__tab is-active">Contatos</a></li>
        <li><a href="/usertracks">User Traking</a></li>
        <!--<li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>-->
        <!--<li><a href="#">Reports</a></li>-->
        <!--<li><a href="#">Analytics</a></li>-->
        <!--<li><a href="#">Export</a></li>-->
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <h2 class="sub-header"><%= @title %></h2>
      <div class="table-responsive">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="/bootstrap-dist/js/bootstrap.min.js"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="/bootstrap-dist/js/holder.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/bootstrap-dist/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/usertracks/_form.html.erb
<%= form_for(usertrack) do |f| %>
  <% if usertrack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usertrack.errors.count, "error") %> prohibited this usertrack from being saved:</h2>

      <ul>
      <% usertrack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guid %>
    <%= f.text_field :guid %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :datetime %>
    <%= f.text_field :datetime %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertracks/edit.html.erb
<h1>Editing Usertrack</h1>

<%= render 'form', usertrack: @usertrack %>

<%= link_to 'Show', @usertrack %> |
<%= link_to 'Back', usertracks_path %>

app/views/usertracks/index.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <th>Guid</th>
    <th>Url</th>
    <th>Datetime</th>
  </tr>
  </thead>
  <tbody>
    <% @usertracks.each do |usertrack| %>
      <tr>
        <td><%= usertrack.guid %></td>
        <td><%= usertrack.url %></td>
        <td><%= usertrack.datetime %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/usertracks/new.html.erb
<h1>New Usertrack</h1>

<%= render 'form', usertrack: @usertrack %>

<%= link_to 'Back', usertracks_path %>

app/views/usertracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guid:</strong>
  <%= @usertrack.guid %>
</p>

<p>
  <strong>Url:</strong>
  <%= @usertrack.url %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @usertrack.datetime %>
</p>

<%= link_to 'Edit', edit_usertrack_path(@usertrack) %> |
<%= link_to 'Back', usertracks_path %>